### PR TITLE
Export function fix

### PR DESCRIPTION
**Pull request by ywg**
Hi, I've made some few changes to the 3 export functions.

First, I changed "tempArr" arrays to "listItem" objects, The reason for this is that javascript arrays are not like PHP arrays, you shouldn't use them to store Key/Value pairs. Arrays should be used only for flat lists, Objects should be used for Key/Value maps.

One of the problem in using Arrays instead of objects is that your output isn't serializable, which is a real problem for an export function.

```javascript
console.log(JSON.stringify($('#sTree2').sortableListsToArray()));

// Before
[[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]]

// Now
[{"id":"item_a","order":0},{"id":"item_b","order":1},{"id":"item_b1","parentId":"item_b","order":0},{"id":"item_b2","parentId":"item_b","order":1},{"id":"item_b3","parentId":"item_b","order":2},{"id":"item_b4","parentId":"item_b","order":3},{"id":"item_b5","parentId":"item_b","order":4},{"id":"item_c","order":2},{"id":"item_c1","parentId":"item_c","order":0},{"id":"item_c2","parentId":"item_c","order":1},{"id":"item_c3","parentId":"item_c","order":2},{"id":"item_c4","parentId":"item_c","order":3},{"id":"item_c5","parentId":"item_c","order":4},{"id":"item_d","order":3},{"id":"item_d1","parentId":"item_d","order":0},{"id":"item_d2","parentId":"item_d","order":1},{"id":"item_d3","parentId":"item_d","order":2},{"id":"item_d4","parentId":"item_d","order":3},{"id":"item_d5","parentId":"item_d","order":4},{"id":"item_e","order":4},{"id":"item_f","order":5}]
```

All other changes are pretty self explanatoring

* Use 0 indexed counter for order to prevent having an undefined first
child at index 0
* Changed "branchOrder" to "order" for coherency between Array and
Hierarchy export
* Removed unnecessary variable declarations that shadowed arguments
* ToString export was not properly escaping component and ampersand separator didn't need to be encoded

### CODE REVIEW

**Comment by ywg** [comment]
The problem with `order = 1` was in fonction `toHierarchy` when you had `arr[order++] = listItem` it was generating child lists with a null items at index 0.

If you revert those two lines you'll have this.

```javascript
console.log(JSON.stringify($('#sTree2').sortableListsToHierarchy()));

[  
   null,
   {  
      "id":"item_a",
      "order":1,
      "children":[  

      ]
   },
   {  
      "id":"item_b",
      "order":2,
      "children":[  
         null,
         {  
            "id":"item_b1",
            "order":1,
            "children":[  

            ]
         },
         {  
            "id":"item_b2",
            "order":2,
            "children":[  

            ]
         },
         {  
            "id":"item_b3",
            "order":3,
            "children":[  

            ]
         },
         {  
            "id":"item_b4",
            "order":4,
            "children":[  

            ]
         },
         {  
            "id":"item_b5",
            "order":5,
            "children":[  

            ]
         }
      ]
   },
   {  
      "id":"item_c",
      "order":3,
      "children":[  
         null,
         {  
            "id":"item_c1",
            "order":1,
            "children":[  

            ]
         },
         {  
            "id":"item_c2",
            "order":2,
            "children":[  

            ]
         },
         {  
            "id":"item_c3",
            "order":3,
            "children":[  

            ]
         },
         {  
            "id":"item_c4",
            "order":4,
            "children":[  

            ]
         },
         {  
            "id":"item_c5",
            "order":5,
            "children":[  

            ]
         }
      ]
   },
   {  
      "id":"item_d",
      "order":4,
      "children":[  
         null,
         {  
            "id":"item_d1",
            "order":1,
            "children":[  

            ]
         },
         {  
            "id":"item_d2",
            "order":2,
            "children":[  

            ]
         },
         {  
            "id":"item_d3",
            "order":3,
            "children":[  

            ]
         },
         {  
            "id":"item_d4",
            "order":4,
            "children":[  

            ]
         },
         {  
            "id":"item_d5",
            "order":5,
            "children":[  

            ]
         }
      ]
   },
   {  
      "id":"item_e",
      "order":5,
      "children":[  

      ]
   },
   {  
      "id":"item_f",
      "order":6,
      "children":[  

      ]
   }
]
```

**Comment by camohub** [comment]
Ok thanks, any new idea?

**Comment by ywg** [comment]
The baseElement trick worked like a charm.

However, I had to do some other changes to successfully integrate your library in my project 

* I added an option "ignoreClasses" because my list items contained buttons, and I needed to be able to click thoses without entering drag mode
* I missed an "onDragStart" callback
* There is a problem with the "complete" callback. It fires before the drop animation being completed, when the placeholder and the hint are still appended on the list and the dragged item isn't.
* I modified the "dragging" function so if it has an isAllowed callback it made smarter choices about insertion point
* I added special css classes like "no-nesting" and "force-rooting" so that most simple trees can be implemented without using "isAllowed" callback.

I'll try to take some time this week-end to put that in different branches and send you pull requests.

**Comment by camohub** [comment]
I would like to see that. It sounds good.

**Pull request merged**
